# Generated by Django 4.2.7 on 2025-08-26 12:42

from django.db import migrations, models
import sqlalchemy.sql._elements_constructors


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=sqlalchemy.sql._elements_constructors.false, unique=True),
            preserve_default=sqlalchemy.sql._elements_constructors.false,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
